version: "3.8"
services:
    vue-app:
        build:
            context: .
            dockerfile: Dockerfile
        
        container_name: vue-app
        ports:
            - 8080:80
    nginx:
        image: nginx:alpine
        container_name: nginx-app
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - NODE_ENV=development
        ports:
            - 80:80
        depends_on:
            - app